version: '3.9'

services:
  backend:
    depends_on:
      - psql
      - redis
    build: .
    env_file:
      - .env
    networks:
      - net
    ports:
      - 8080:8080

  psql:
    image: postgres:alpine
    hostname: ${PSQL_HOSTNAME}
    networks:
      - net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${PSQL_NAME}
    volumes:
      - psql-data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    hostname: ${REDIS_HOSTNAME}
    networks:
      - net
    ports:
      - 6380:6379
      - 8001:8001
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  psql-data:
    driver: local
  redis-data:
    driver: local

networks:
  net:
    driver: bridge
