spring:
  datasource:
    url: jdbc:postgresql://${PSQL_HOSTNAME}:5432/${PSQL_NAME}
    username: ${PSQL_USER}
    password: ${PSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      hostname: ${REDIS_HOSTNAME}

jwt:
  secret: ${SECRET}
